### ISSUE TITLE
create admin phal

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/raspbian-ovos#15]
a new step creating system service for admin phal should be added [here](https://github.com/OpenVoiceOS/ovos-picroft/blob/main/stage-picroft/00-build/01-run.sh#L39), this is the only ovos component running as root

docs
https://openvoiceos.github.io/community-docs/PHAL/#admin-phal

**Comment by builderjer** [comment]
I have this to where it installs and is `vendor enabled`, but can't get it to auto start on boot.  I started a team chat to try and get some help.

**Comment by builderjer** [comment]
This is fixed in the last `dev` branch commit
