### ISSUE TITLE
Temperature incorrect when system_unit set to "english"

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#42]
Running raspbian-ovos-dev.zip (4/3/2023) on a 3B+
After a clean install, I ran ovos-cli-client.
I asked "What is the weather"
and the answer was 13 degrees celsius (correct!)
Then I ran ovos-config set -k system_unit  "english"
and asked "What is the weather"
and the answer was 286 degrees.

**Comment by builderjer** [comment]
Try `imperial ` instead of English. And actually,  this is a skill issue. I will move it if imperial does not work

**Comment by emphasize** [comment]
can confirm this issue with weather as i'm implementing a fix for requesting a different scale per utterance (you wouldn't need to change the settings). Bit odd though, since the skill is not "doing the math", just restating what is sent.

-> skill issue

**Comment by Bulwagga** [comment]
"imperial" works, "english" does not.  I picked "english" out of some mycroft documentation, so you'll likely be faced with this again.  Could I suggest an enhancement? Extend the ovos-config dialog to replace the word "english" automatically with the word "imperial"? Or as a more general change, trap bad keywords and suggest alternatives?  Thank you, I am otherwise all set.

**Comment by emphasize** [comment]
Still an issue in the skill as it requests 
```
"GET /v1/owm/onecall?exclude=minutely&lang=de&lat=49.5875&lon=8.35778&units=fahrenheit HTTP/1.1" 200 -
```
(per utterance) But none of your concern. Have to change that param to imperial.

**Comment by emphasize** [comment]
btw also a problem with ovos-config. you shouldnt be able to pass "a-string-to-your-liking" to the config
