### ISSUE TITLE
Locale setup

### ISSUE THREAD

**Issue by emphasize** [OpenVoiceOS/raspbian-ovos#46]
things to adjust:

* locale-gen en_US.UTF-8 (wouldn't know why pi-gen is not generating the locale)
* toss `export <lang>` in `.bash_profile`
* readd package `keyboard-configuration` and `console-setup` for keyboard setup
* tbc

**Comment by builderjer** [comment]
fixed [here](https://github.com/OpenVoiceOS/pi-gen/commit/c4143ff92469e92a3e534c891bd28e1e84d09437)
and [here](https://github.com/OpenVoiceOS/pi-gen/commit/f1a55abd10bff573e1798648ca0dc6bb58cf1b48)
