### ISSUE TITLE
Power save disable

### ISSUE THREAD

**Issue by erikjber** [OpenVoiceOS/raspbian-ovos#47]
The Raspberry Pi WiFi power-save feature is known to cause problems for devices connected via WiFi for a prolonged time.  
It would be an improvement if this "feature" was disabled out of the box.

**Comment by j1nx** [comment]
https://github.com/OpenVoiceOS/ovos-buildroot/blob/develop/buildroot-external/board/ovos/raspberrypi/rootfs-overlay/base/usr/lib/systemd/system/wifi_powersave@.service

**Comment by denics** [comment]
upvote to include this in the image 👍

**Comment by builderjer** [comment]
This is included in the newest dev image
https://ovosimages.ziggyai.online/raspbian/development/
