### ISSUE TITLE
Move logs files to ramdisk

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/raspbian-ovos#49]
Has the image comes with a 20Mb RAM disk, I think it should be good to move the log files under .local/state/mycroft/*.log to /ramdisk

**Comment by builderjer** [comment]
This is done in the newest dev image
https://ovosimages.ziggyai.online/raspbian/development/
there are sys-links from `/ramdisk/mycroft` to `~/.local/state/mycroft` so the default paths still work
