### ISSUE TITLE
No internet radio.  With clean install: ERROR - The TTS plugin "ovos-tts-plugin-piper" could not be loaded.

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#51]
After installing [raspbian-ovos-headless.zip](https://downloads.openvoiceos.com/images/raspbian/raspbian-ovos-headless.zip) on a 3B+, the audio log shows that "The TTS plugin "ovos-tts-plugin-piper" could not be loaded."  Somewhat later there is a message "ERROR - Audio service failed to launch (No TTS loaded)".

I load espeak phonemizer with 
sudo apt-get --assume-yes install libespeak-ng1 espeak-ng
and
pip install espeak-phonemizer

Then audio.log shows me "ERROR - The TTS plugin "ovos-tts-plugin-mimic" could not be loaded." and again the audio service fails to launch with (unkown plugin).

Then I add mimic with
pip install ovos-tts-plugin-mimic

What else do I need to do to hear internet radio?  I've tried several of the OCP skills and I'm having trouble getting my utterances recognized so I wrote a simple skill that gets me to the point of 

stream-player-skill:handle_stream_intent:40 - INFO - playing http://playerservices.streamtheworld.com/api/livestream-redirect/WAMCHD2.
mp3

but I'm still getting no sound.  Any suggestions?  mpg123 of the same link gives me the audio correctly, so at least some of my audio system is correct.

Thank you

**Comment by Bulwagga** [comment]
After looking into the image build process, it looks to me like ovos-tts-plugin-mimic was already loaded during the system build. I will create another issue if I can find an earlier instance of any ovos-tts-plugin-mimic issues.

**Comment by builderjer** [comment]
There are issues with missing 
espeak packages, i think. I don't remember off the top of my head, but they will be in the next build

**Comment by Bulwagga** [comment]
No worries...  I just did a line-by-line through the first boot log from the first run of my most recent raspbian image.  No mention of issues with ovos-tts-plugin-mimic.  My sense is to let  this go until we build an image with piper & espeak packages and then see if it still has trouble finding mimic. I saw two other issues I will enter here.

**Comment by Bulwagga** [comment]
I did my own build and install and ovos-tts-plugin-mimic completed successfully with no odd messages of any kind. One thought I has related to the message "Defaulting to user installation because normal site-packages is not writeable." Is there any chance that a component of the audio service is looking for mimic in it's "normal" location?

**Comment by builderjer** [comment]
That is normal when installing pip packages without sudo.

**Comment by Bulwagga** [comment]
Good to know... I guess I had been thinking that one of the python packages had been looking for ovos-tts-plugin-mimic in its "sudo" location and not finding it there.

**Comment by builderjer** [comment]
The user packages will take priority if they are installed. Most should be fine. Any packages that need sudo privileges should say so

**Comment by builderjer** [comment]
I am going to close this as `ovos-tts-plugin-piper` loads now, but is unused for now.  The image defaults to `ovos-tts-server-plugin` with default public servers.

The other "internet radio" can be opened in another issue of its own
