### ISSUE TITLE
Wordnet not installed in raspbian image

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#52]
I noticed this when I was building my own copy of OVOS.  The build log tells me that the wordnet needed to be installed and says how.  Here is the error message:
ovos-systemd-skills[670]: [nltk_data] Error loading wordnet: <urlopen error [Errno -3] Temporary failure in name resolution>
ovos-systemd-skills[670]: [nltk_data] Error loading omw-1.4: <urlopen error [Errno -3] Temporary
failure in name resolution>
ovos-systemd-skills[670]: [nltk_data] Error loading wordnet: <urlopen error [Errno -3] Temporary
failure in name resolution>
ovos-systemd-skills[670]: [nltk_data] Error loading omw-1.4: <urlopen error [Errno -3] Temporary
failure in name resolution>

The solution is to do something like this:
python3 << DONE
import nltk
nltk.download('wordnet')
quit()
DONE

**Comment by builderjer** [comment]
Not sure where this dependency is coming from. I have never had to install that before

**Comment by Bulwagga** [comment]
This dependency apparently comes from using ovos-listener.  As we are moving away from ovos-listener to adopt dinkum-listener, I am closing this.

**Comment by JarbasAl** [comment]
this came from ovos-classifiers, which is used in skills service  (normalizing utterances step)

should be optional and i think that was fixed in latest release
