### ISSUE TITLE
Clean raspbian-lite install. Failed to start ovos.service: Unit ovos.service not found.

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#56]
This may well be an oversight on my part, but I think I followed the instructions.

Following documentation at https://github.com/OpenVoiceOS/ovos-technical-manual/blob/master/docs/raspbian_ovos.md using a 3B+

Downloaded and modified the latest raspbian-lite image (this step is where I believe the user error happened). Then
   sudo apt install build-essential python3-dev python3-pip swig libssl-dev libfann-dev portaudio19-dev libpulse-dev cmake git libncurses-dev pulseaudio-utils
   cd
   git clone https://github.com/OpenVoiceOS/raspbian-ovos.git
   cd raspbian-ovos
   ./manual_install.sh 

There was a repeated warning message:
  WARNING: The script * is installed in '/home/ovos/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no->

The script ended with ovos failing to start:
Failed to start ovos.service: Unit ovos.service not found.

"systemctl --user start ovos" also produces the ovos.service not found message

There are some errors in the output:
****

Installing systemd files

cp: cannot stat 'stage-ovos/00-build/files/usr/libexec/ovos*': No such file or directory
chmod: cannot access '/home/ovos/.local/bin/ovos-systemd*': No such file or directory
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting sdnotify
  Downloading https://www.piwheels.org/simple/sdnotify/sdnotify-0.3.2-py3-none-any.whl (3.5 kB)
Installing collected packages: sdnotify
Successfully installed sdnotify-0.3.2
cp: cannot stat 'stage-ovos/00-build/files/usr/lib/systemd/user/*': No such file or directory

Done installing systemd files

Installing extra skills

****

It dawned on me that I might not have answered the prompts correctly so I looked back in the scroll and I think this looks ok:

![Screenshot from 2023-05-27 15-47-10](https://github.com/OpenVoiceOS/raspbian-ovos/assets/10997829/d4347af7-485a-467c-b778-19a1cb70d328)

**Comment by builderjer** [comment]
To be honest, that script  was a hack to test with. It will ONLY work on the dev branch,  and I'm not sure even then. There have been package changes since I wrote this. For instance,  it does not contain any reference to dinkun-listener. I think the script itself is handy to have, and an update should be done with new packages ans systemd files. PR's are more than welcome,  and should be as simple as changing/addind/removing a few lines.

**Comment by Bulwagga** [comment]
LOL! Well, it looked pretty good to me. Given the docs, I had thought it was the script you use to create the build image. I *was* puzzled by the lack of dinkum-listener but figured it was just one of the many things I don't understand yet.  As for PR's, I'll work towards that but it may be have to wait until I can generate a useful suggestion. :)

**Comment by Bulwagga** [comment]
@builderjer Is the process described at https://github.com/OpenVoiceOS/ovos-technical-manual/blob/master/docs/raspbian_ovos.md your vision of how we will be building our local copies of headless OVOS? To me it seems to be a logical and easy to follow process that would bring more people to the headless platform. I had been developing a script to customize the *images* as they came out, but it makes more sense to me that I create my own local instance with a script that could be an enhanced "manual_install.sh". Leading me to the conclusion that *if it is on your roadmap* I should be working towards a fully functional manual_install.sh. Thoughts?
