### ISSUE TITLE
Image download site is offline

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#74]
https://ovosimages.ziggyai.online/raspbian/development is offline

**Comment by builderjer** [comment]
We had a lightning storm last Thursday/Friday and it knocked stuff out. I left out of town for work Friday morning before things got fixed. Something at my house did not restart correctly and I have nobody there to look at it. I should be back home in the next couple of days and will fix it. 

For now, I have the latest image [here](https://drive.google.com/file/d/1WDP8EYTFxYn6hvZxyfPGWYk96X37iPQx/view?usp=drivesdk)

**Comment by Bulwagga** [comment]
Thanks!

**Comment by builderjer** [comment]
All back up for now
