### ISSUE TITLE
 manual_user_install.sh  fails on install with clean RasPI OS Lite (64-bit)

### ISSUE THREAD

**Issue by Bulwagga** [OpenVoiceOS/raspbian-ovos#88]
The ordering of the install ends up attempting to create the venv before python3-venv is installed.

I ended up inserting

 `echo $sudoPW | sudo -S apt install -y python3-dev python3-pip python3-venv`

just before the block where the ovos venv is created, but there may better ways to fix this.
Thanks

**Comment by builderjer** [comment]
Can't think of a much better way than to install the packages it needs before they are used.

**Comment by builderjer** [comment]
Fixed with [this](https://github.com/OpenVoiceOS/raspbian-ovos/commit/f1a47828075d9a0b4c31c158335b5a25a37c9c51)
