### ISSUE TITLE
ERROR - [Errno2] No such file or directory: 'paplay'

### ISSUE THREAD

**Issue by dickorydock** [OpenVoiceOS/raspbian-ovos#9]
I get this error when running `ovos-cli-client.

I was able to fix it using `sudo apt-get install pulseaudio-utils` maybe add to the guide?

**Comment by builderjer** [comment]
I am working on an updated version now.  Thanks for the insite

**Comment by builderjer** [comment]
This install guide uses the latest code from git.  When you installed precise-lite, it used the version on PyPi which created some dependency issues.  
I would suggest using `--pre` in your pip command
`pip install --pre ovos-ww-plugin-precise-lite`

I am not sure how to fix this other than starting over

**Comment by dickorydock** [comment]
Before I try that again with --pre, cna you clarify whether the wakeword is supposed to work with just the `ovos-core` from git?

**Comment by builderjer** [comment]
@dickorydock has this been resolved?

**Comment by builderjer** [comment]
I think all of these have been resolved in the dev branch.  I am closing this, but feel free to open another with new info
