### ISSUE TITLE
uninstall option from manual_user_install

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/raspbian-ovos#94]
It was recently mentioned in the chats if there is a `clean` command or `uninstall`.  I think that this would be useful for users to start over with.

**Comment by Bulwagga** [comment]
I'll be able to start putting something together within the next few weeks.

**Comment by builderjer** [comment]
I recently changed the systemd  services to use a venv, and I think the manual install script has a `sed ` command changing them. You might look there also

**Comment by builderjer** [comment]
Completed [here](https://github.com/OpenVoiceOS/raspbian-ovos/pull/100)
